### ISSUE TITLE
downscaler/downtime-replicas annotation does not work on a namespace level

### ISSUE THREAD

**Issue by kuzmacska** [caas-team/py-kube-downscaler#126]
Overriding default flag on a namespace level annotation does not work.

```apiVersion: v1
kind: Namespace
metadata:
  annotations:
    downscaler/downtime-replicas: "1"
  labels:
    kubernetes.io/metadata.name: test
  name: test
  resourceVersion: "2913332799"
```

The namespace is being ignored by the kube-downscaler. Not scaling to zero, nor to 1.

Using kube-downscaler version v24.12.0.

**Comment by kuzmacska** [comment]
Workaround is to use `--downtime-replicas=0` in the py-kube-downscaler configuration explicitly

**Comment by samuel-esp** [comment]
Hi @kuzmacska sorry for my late reply? Could you upload the configurations of your kube-downscaler instance (Deployment and ConfigMap)? If the namespace is being ignored entirely I suspect it could be caused by a wrong target configuration

**Comment by enviroQL** [comment]
Hi @samuel-esp , this does not work for me seems, am I missing anything:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-deployment
  annotations:
    downscaler/downtimePeriod: "Mon-Fri 01:00-05:00 UTC"
    downscaler/minReplicas: "0"
```

the scaler only works when `DEFAULT_DOWNTIME` set, but seems can't pick up the annotations?
