### ISSUE TITLE
Chart 0.3.1 broken RBAC template

### ISSUE THREAD

**Issue by george-c29** [caas-team/py-kube-downscaler#147]
Hi, using the following values:
```
py-kube-downscaler:
  arguments:
    - --include-resources=deployments,statefulsets,horizontalpodautoscalers,daemonsets,cronjobs
    - --interval=60

  constrainedDownscaler: true

  constrainedNamespaces:
    - monitoring
    - logging-elastic
    - prometheus-blackbox-exporter-system
    - realistic-ndt
    - realistic-zqn
    - kube-haveged
  #  - realistic-dev
  #  - realistic-cert

  serviceAccount:
    create: true
    annotations: {}
    name: "py-kube-downscaler"

  podAnnotations: {}

  podSecurityContext:
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    supplementalGroups: [1000]

  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
        - ALL

  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  excludedNamespaces:
    - py-kube-downscaler
    - kube-downscaler
    - kube-system
    - argo-cd-system
    - karpenter

  extraConfig: |
    DEFAULT_UPTIME: "Mon-Fri 08:00-20:00 CET"
```

in a chart like this:
```
apiVersion: v2
name: downscaler
description: The py-kube-downscaler used for resource downscaling
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
- name: py-kube-downscaler
  version: 0.3.1
  repository: oci://ghcr.io/caas-team/charts
```
results in this:
```
MacBook-Pro:py-kube-downscaler2$ helm install --debug --dry-run downscaler . -f dev-values.yaml > rendered_debug.yaml
install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: /Users/georgecristiancimpoies/Work/WeShape/kubernetes/aws/py-kube-downscaler2

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Role): unknown field "roleRef" in io.k8s.api.rbac.v1.Role, ValidationError(Role): unknown field "subjects" in io.k8s.api.rbac.v1.Role]
helm.go:84: [debug] error validating "": error validating data: [ValidationError(Role): unknown field "roleRef" in io.k8s.api.rbac.v1.Role, ValidationError(Role): unknown field "subjects" in io.k8s.api.rbac.v1.Role]
helm.sh/helm/v3/pkg/kube.scrubValidationError
        helm.sh/helm/v3/pkg/kube/client.go:632
helm.sh/helm/v3/pkg/kube.(*Client).Build
        helm.sh/helm/v3/pkg/kube/client.go:204
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:275
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:264
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:125
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_arm64.s:1133
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:277
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:264
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:125
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_arm64.s:1133
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_arm64.s:1133
```

Templating shows that there is a missing separator between Role and RoleBinding:
```
# Source: downscaler/charts/py-kube-downscaler/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-py-kube-downscaler
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-py-kube-downscaler
subjects:
  - kind: ServiceAccount
    name: py-kube-downscaler
    namespace: kube-downscaler
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-py-kube-downscaler
  namespace: logging-elastic
```

I'm guessing we need to add a separator here:
https://github.com/caas-team/py-kube-downscaler/blob/main/chart/templates/rbac.yaml#L135
