### ISSUE TITLE
ConfigMap 

### ISSUE THREAD

**Issue by GreyGlass1** [caas-team/py-kube-downscaler#36]
Hi, I’ve been testing different options of the solution today with success, except for using the config map to down-scale all deployments. Can you confirm if this is a bug or if there’s an issue with my ConfigMap?

```
k get configmap py-kube-downscaler -n py-kube-downscaler -oyaml
apiVersion: v1
data:
  DEFAULT_DOWNTIME: Mon-Fri 15:54:-16:00 Europe/London
  EXCLUDE_NAMESPACES:kube-system, py-kube-downscaler
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kube-downscaler
    meta.helm.sh/release-namespace: py-kube-downscaler
  labels:
    app.kubernetes.io/managed-by: Helm
  name: py-kube-downscaler
  namespace: py-kube-downscaler
```

Thanks.

**Comment by Fovty** [comment]
At first glance, the space between the EXCLUDE_NAMESPACES seems to be too much.

`EXCLUDE_NAMESPACES:kube-system,py-kube-downscaler`

I'll have a closer look tomorrow. Please let me know if this changes anything.

This would refer to:

- https://github.com/caas-team/py-kube-downscaler/issues/33
- https://github.com/caas-team/py-kube-downscaler/pull/25
- https://github.com/caas-team/py-kube-downscaler/pull/27

**Comment by Fovty** [comment]
Ok, there seem to be some other issues with your config map.

- **Quotes Around Strings**: Make sure the values for DEFAULT_DOWNTIME and EXCLUDE_NAMESPACES are quoted properly. This helps avoid issues with parsing times and lists.
- **Spacing and Formatting**: Ensure there are no extra spaces or formatting issues. For example, there should be a space after the colon in EXCLUDE_NAMESPACES.
- The original value had an extra colon before -16:00, which might be a typo. It should be formatted as "Mon-Fri 15:54-16:00 Europe/London".

```
apiVersion: v1
data:
  DEFAULT_DOWNTIME: "Mon-Fri 15:54-16:00 Europe/London"
  EXCLUDE_NAMESPACES: "kube-system,py-kube-downscaler"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kube-downscaler
    meta.helm.sh/release-namespace: py-kube-downscaler
  labels:
    app.kubernetes.io/managed-by: Helm
  name: py-kube-downscaler
  namespace: py-kube-downscaler
```

This ConfigMap didn't throw any obvious formatting issues on my side

`kubectl apply -f path/to/your/configmap.yaml`
