### ISSUE TITLE
`403 Client Error: Forbidden for url: https://172.20.0.1:443/apis/batch/v1/jobs` when seting `jobs` in `--include-resources=`

### ISSUE THREAD

**Issue by vmignot** [caas-team/py-kube-downscaler#97]
First, thanks for this fork :-)

## Issue
Helm Chart: v0.2.8
Kubernetes: v1.29.7-eks-a18cd3a

```yaml
# values.yaml
...
  extraConfig: |
    DEFAULT_UPTIME: ""
    DEFAULT_DOWNTIME: ""

  arguments:
  - --interval=60
  - --grace-period=60
  - --include-resources=jobs,deployments,statefulsets,horizontalpodautoscalers,scaledobjects,cronjobs,daemonsets,poddisruptionbudgets
  - --matching-labels=".*"
...
```

### Problem to solve
The only error I have at start is:
```json
{"logtag":"F","time":"2024-09-25T06:18:13.808030888Z","message":"requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://172.20.0.1:443/apis/batch/v1/jobs"}
```

### Proposal

We might missing something in the rbac. Mayber around here? https://github.com/caas-team/py-kube-downscaler/blob/main/chart/templates/rbac.yaml#L179

Thanks in advance for your help :-)
